### ISSUE TITLE
Output compare result with Shiny

### ISSUE THREAD

**Issue by RKonstantinR** [alexsanjoseph/compareDF#13]
There is a way to display $htlm_output with Shiny::htmlOutput function?

**Comment by alexsanjoseph** [comment]
I haven't thought of this use case, really. Can you give me some more info into your use case?

**Comment by RKonstantinR** [comment]
You can see my code example with additional info at stackoverflow:
https://stackoverflow.com/questions/51381762/shiny-output-comparison-results-in-html-format

**Comment by alexsanjoseph** [comment]
I was trying to find a solution for this in the package, but I learned today that shiny has this functionality implemented trivially. You can solve this by adding the shiny::HTML() tag to your output. I've given an example in SO.
