### ISSUE TITLE
rounding doubles to 2 decimal places - what's the purpose?

### ISSUE THREAD

**Issue by grahamgill** [alexsanjoseph/compareDF#18]
compareDF is very useful, thanks.

What's the purpose of the r2two() function, and rounding doubles to 2 decimal places? Shouldn't values be left unrounded and the tolerance setting of compare_df() used to pick what counts as a difference, no matter the scale?

I want to use the data in compare_df(...)$comparison_df for further computation, not just display or summarising changes. I need the reported values to be what they were originally.

I'm working around this at the moment by multiplying doubles columns by 10^n, with whatever n is relevant to my use case, before calling compare_df(), then converting comparison_df back.

**Comment by alexsanjoseph** [comment]
> Shouldn't values be left unrounded and the tolerance setting of compare_df() used to pick what counts as a difference, no matter the scale

That's a very smart idea - Hadn't thought of it. Will make an update soon regarding this.

**Comment by alexsanjoseph** [comment]
I didn't implement rounding as inferred from tolerance because tolerance could be of two types and it gets complicated. I have added a simpler (albeit less elegant) approach of adding a parameter.

@grahamgill - I've pushed a new commit. Can you verify if the new parameter solves the problem?
