### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by msberends** [alexsanjoseph/compareDF#21]
Thank for this great package!

Would it be possible to support markdown too? I would like to print the results in an Rmd file, which seems not possible at the moment. Maybe use `knitr::kable()` to support this?

**Comment by alexsanjoseph** [comment]
Let me see if I understand your request correcly. Can't you just use `knitr::kable(df_compare$comparison_df)` to solve the problem?

**Comment by msberends** [comment]
Yes, figured that one out just now 🙈
