### ISSUE TITLE
maximum upload size exceeded

### ISSUE THREAD

**Issue by karuno11** [alexsanjoseph/compareDF#25]
Hello,

I'm trying to compare 2 data frames that have 24,000 records+ (~5 mb) and I get this error. I used your compareDF package in an R shiny app where the user uploads two CSV files and compares the two. Any help would be greatly appreciated!

**Comment by alexsanjoseph** [comment]
Are you sure the error is in this package? 

https://stackoverflow.com/questions/18037737/how-to-change-maximum-upload-size-exceeded-restriction-in-shiny-and-save-user

Alex :)

**Comment by karuno11** [comment]
Oh yes you're correct! Thank you for the link! That solved my issue.

**Comment by karuno11** [comment]
Hi Alex Joseph,

I have a question about why cells are colored grey. The Read Me says that grey cells are colored because "Cells that haven't changed across the two datasets are colored grey." But in the example with the students, it looks like a row is present in the latest file but not present in the previous file:

[cid:658dbc31-f37a-42e5-882a-bfcb1740df8f]
In this case, why is it colored grey? I would think it would be not colored because it didn't exist in the previous file, which is why the font is green.

Can you clarify why certain rows are colored grey and why some aren't?

Thanks,

Adria
________________________________

**Comment by karuno11** [comment]
I'm referring to the whole row that's highlighted in grey, not the font of the individual values. For example, why is the top row highlighted in grey but not the bottom row (grp change 12 and 13, Rohit and Vikram):




[cid:3de91cac-b9f3-456e-876f-6ddb84ae2ec6]


________________________________

**Comment by alexsanjoseph** [comment]
Which is the row that's fully highlighted in grey? The top row has one cell that's green and hence included

**Comment by karuno11** [comment]
This row:

[cid:e1001670-1874-4a83-a98d-0b40219c7cd2]
Number 12 is fully highlighted in grey but I'm not sure why, compared to row 13. Why is row 12 highlighted in grey? I understand green font means the row is in the new file but not in the old file.

________________________________

**Comment by alexsanjoseph** [comment]
Can you post an actual screenshot? How do I use the cid?

**Comment by karuno11** [comment]
I've attached a screenshot to this email. Please let me know if you can view it.

________________________________

**Comment by alexsanjoseph** [comment]
I'm sorry it's not visible for me

**Comment by karuno11** [comment]
![2](https://user-images.githubusercontent.com/53199135/64612446-d64bd480-d3a1-11e9-9270-84a15a4aafc5.PNG)

**Comment by alexsanjoseph** [comment]
Oh! Now I understand. The background shading doesn't mean anything - it's just there to differentiate alternate groups.
