### ISSUE TITLE
help wanted - HTML output not displaying

### ISSUE THREAD

**Issue by JayCodeLab** [alexsanjoseph/compareDF#27]
Hi,

I appreciate this library!

When I try to run the example, I cannot get the html output? however it runs the "Creating HTML table for first 100 rows"
I'm running the latest version/release of Compare_DF 2.0 and on RStudio Version 1.0.143
NOTE: Excel output works fine.

**Comment by alexsanjoseph** [comment]
Hi Jay - 

You're one of the first people using the new compareDF version! Somethings might be still awry, sorry for that. Can you give a representative example to show the issue that you're facing?

Alex

**Comment by JayCodeLab** [comment]
Hi Alex,

Thanks for your quick reply!

Code: 
`library(compareDF)
library(readxl)
library(openxlsx)
library(htmlTable)


File_New <- read_excel("~/test/FileNew.Xlsx")
File_Old <- read_excel("~/test/FileOld.Xlsx")

ctable_compare = compare_df(File_New,File_Old, c("Server"))
ctable_compare$comparison_df

#HTML output
create_output_table(ctable_compare)
view_html(ctable_compare)

#excel output
create_output_table(ctable_compare, output_type = 'xlsx', file_name = "test_file.xlsx")`

Quite new to "coding/scripting"..

**Comment by alexsanjoseph** [comment]
@JayCodeLab 

`create_output_table(ctable_compare)` This function should have already created the output in the viewer without using the view_html command.

However, there was an issue with view_html function which I have fixed in the latest version. Can you try using the latest version of the package? 

devtools::install_github('alexsanjoseph/compareDF')

If you want to write HTML to a file, use the same format as before

create_output_table(ctable_compare, output_type = 'html', file_name = "test_file.html")`

**Comment by JayCodeLab** [comment]
Hi Alex,
Seems to be working now! Thank you so much!

**Comment by alexsanjoseph** [comment]
What's the issue @JayCodeLab ?

**Comment by JayCodeLab** [comment]
Hi Alex,

I can get the view_html command to work. However, the create_output_table(ctable_compare) doesn't work.

Thanks Alex.

**Comment by alexsanjoseph** [comment]
Can you explain a bit what you want to do? Also an example would help me understand the issue

**Comment by JayCodeLab** [comment]
Hi again,

Just trying to run your code.

I can't get the  create_output_table(ctable_compare) to output the results in the viewer.


CODE:
library(compareDF)
library(readxl)
library(openxlsx)
library(htmlTable)


File_New <- read_excel("~/test/FileNew.Xlsx")
File_Old <- read_excel("~/test/FileOld.Xlsx")

ctable_compare = compare_df(File_New,File_Old, c("Server"))
ctable_compare$comparison_df

#HTML output
create_output_table(ctable_compare)
#view_html(ctable_compare)

#excel output
create_output_table(ctable_compare, output_type = 'xlsx', file_name = "test_file.xlsx")

**Comment by alexsanjoseph** [comment]
Do you mean that the function runs, but the output is not displaying in the viewer? I was able to view it without any issue?

1) Can you write it to an HTML file and see?
2) Are you on the latest version of the package?
3) Can you give your System information? (`sessionInfo()`)

**Comment by JayCodeLab** [comment]
Hi Alex,
It works now, thank you! Not sure why, I restarted my R and it pop up!
However, I found a new issue - will make a new threat for that,
