### ISSUE TITLE
Color output not the same in the .xlsx file and output (in viewer)

### ISSUE THREAD

**Issue by JayCodeLab** [alexsanjoseph/compareDF#28]
Hi Alex,

![image](https://user-images.githubusercontent.com/59565565/72255803-fb7a7900-3607-11ea-9c3d-252c844aacf7.png)

I generated the following comparison, however the coloring is not the same. The one in the viewer is the correct one, in my opinion.

Thanks.

/Jay

**Comment by alexsanjoseph** [comment]
Thanks @JayCodeLab - Does seem to be a bug - Thanks for the great examples, too. Can you try the latest dev version from master ?

**Comment by JayCodeLab** [comment]
Hi again @alexsanjoseph,

Seems to work! 
![image](https://user-images.githubusercontent.com/59565565/72258656-e9500900-360e-11ea-8dab-f87217e3c792.png)

Thanks!
