### ISSUE TITLE
[create_output_table] color code bugs with xlsx export

### ISSUE THREAD

**Issue by pamdx** [alexsanjoseph/compareDF#29]
Hey guys,

Thanks a lot for this awesome package, it's helping me a lot in my work!

Just wanted to point out a bug I've been running into. For some reason, when I export my comparison table in Excel, the color code in the table becomes incoherent (as opposed to exporting in html, which creates tables with the expected color code).

More specifically, when cell values are replaced between the new and the old datasets, the xlsx export will show additions in red and removals in green.

Here's an example showing the difference in (1) xlsx and (2) html exports:

![image](https://user-images.githubusercontent.com/59026485/72350199-3fd84880-36de-11ea-831a-6d84e4ba69c5.png)

![image](https://user-images.githubusercontent.com/59026485/72350240-57afcc80-36de-11ea-8496-4329e2f117d5.png)

I'm using **R version 3.6.1** (2019-07-05) and **compareDF version 2.0.0**

**Comment by alexsanjoseph** [comment]
This is a known bug. Can you try installing the development version? It
will be fixed in the next CRAN update as well

**Comment by pamdx** [comment]
Ok great to hear, thanks for the quick answer!

**Comment by alexsanjoseph** [comment]
Keeping this open until the next cran release

**Comment by alexsanjoseph** [comment]
I've pushed the bugfix to CRAN. Closing issue
