### ISSUE TITLE
labeling additions vs removals

### ISSUE THREAD

**Issue by sngordon** [alexsanjoseph/compareDF#3]
Just ran my first compare_df (version 1.1.1 in R 3.3.2), looks like a great package!

However I'm confused by the labeling of additions vs removals from $change_count & summary. In your blog entry example, Dhakkan & Mugger are dropped when moving from the old to new dataframe, yet they are listed as "1" under additions and similarly new records are counted under removals. Am I just not conceptualizing this correctly?

**Comment by alexsanjoseph** [comment]
Thanks, @sngordon! There was a bug in the way the changes were calculated. Can you see if it works as expected in the dev version?

**Comment by alexsanjoseph** [comment]
I wonder why the dependency packages didn't get installed :/. Anyway glad to see you got it working! Closing the thread now.
