### ISSUE TITLE
Error installing package from github

### ISSUE THREAD

**Issue by jamesguinnip** [alexsanjoseph/compareDF#30]
Hello,

I first installed _compareDF_ from the CRAN yesterday, and things were great! However, I tried using create_output_table() with output_type = "xlsx" and it wouldn't work. It output an unspecified file type to the working directory and I couldn't get my Windows machine to open the file at all after trying a variety of software.

I noticed the mention of a bug with the CRAN version, so I entered the following to install the package directly from GitHub:
devtools::install_github('alexsanjoseph/compareDF')

Unfortunately, I'm getting the following error message (the copied text includes other info from the console after running the above line of code):

Downloading GitHub repo alexsanjoseph/compareDF@master
√  checking for file 'C:\Users\jguinnip\AppData\Local\Temp\RtmpU31KEH\remotesf34695a6f82\alexsanjoseph-compareDF-9d508d0/DESCRIPTION' (625ms)
-  preparing 'compareDF':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'compareDF_2.0.1.tar.gz'
   
Installing package into ‘\\sunfish/home/jguinnip/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
'\\sunfish\home\jguinnip\Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'compareDF' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in findpack(package, lib.loc) : 
  there is no package called 'compareDF'
Calls: <Anonymous> -> findpack
Execution halted
ERROR: lazy loading failed for package 'compareDF'
* removing '\\sunfish/home/jguinnip/Documents/R/win-library/3.6/compareDF'
Error: Failed to install 'compareDF' from GitHub:
  (converted from warning) installation of package ‘C:/Users/jguinnip/AppData/Local/Temp/RtmpU31KEH/filef34311b57c5/compareDF_2.0.1.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

I appreciate any help you can offer. I'm not very savvy on the back end of R (I'm an ecologist that uses R for statistics) so I'm a little confused about what the error is really telling me. I've used install_github() for other packages in the past with no issues, so I'm not sure what is wrong now.

**Comment by alexsanjoseph** [comment]
I'm not sure what exactly is happening either - because I don't have a windows system with me.

Can you try cloning the repo locally and installing with `R CMD INSTALL .` from the compareDF folder?

**Comment by alexsanjoseph** [comment]
I don't know what exactly the issue was, but I've pushed the bugfix to CRAN - this should solve your issue if it still persists!
