### ISSUE TITLE
More flexible output, side-by-side as an option

### ISSUE THREAD

**Issue by D3SL** [alexsanjoseph/compareDF#34]
It occurred to me while I was comparing a number of very large files that row based output is really only good for eyeballing small amounts of simple data. If the current outputs were offered in column based format a whole lot more could be done with it. 

Everything in R is column oriented and when the differences are listed as ```key old.x new.x old.y new.y``` that information is much more programmatically accessible. Calculations based on differences, much more flexible output formatting, use outside of R in things like pivot tables, more than 2 items could be compared ```purr::reduce()``` style. Modifications would be easier to spot as well in any comparison with a key column. If the key exists in both objects and other columns' values are not identical it's a modification rather than full addition/subtraction.

**Comment by alexsanjoseph** [comment]
Hi @D3SL -

The decision to give a wide output is intentional, as in makes visual comparison easy first up. That said, the output is also provided in `comparison_df` object which can be further manipulated in any of the ways that you mentioned for specific problems one may have. Have you tried this approach?

Maybe I'm not following you completely, so can you help me understand this problem with some reprex?

**Comment by D3SL** [comment]
Sure, I actually did find a package that does this but unlike compare_df it's heavily limited in that it only shows rows which exist in both dataframes. It's also not as human-friendly imho. Between the two of you there's the perfect data-content comparison package.

![image](https://user-images.githubusercontent.com/63225966/88828868-7c7c1500-d1d4-11ea-8073-7d0ea3e3d451.png)

**Comment by alexsanjoseph** [comment]
Thanks for the example, tt's an interesting use case. I have a couple of questions, though

1) Why is this something that's not achieved by a pivot_wider from the compare_df output, depending on the specifics of how the user?
2) How do you deal with cases when one row/group has been replaced by more than one observation?

**Comment by D3SL** [comment]
1. Pivoting sort of works. You need to have a single key column to start with, add a marker column to track whether each object is the new or old data, and the tradeoff is you lose the chng_type column and you'll only have one copy of your key column with both dataframes' worth of rows in it as opposed to a fully side-by-side comparison. You also need to go through long to get to wide.

2.  That would actually be even more clear in a side-by-side format. The old data only has the original row, the new data has multiple rows.  NAs are inserted where needed.

**Comment by alexsanjoseph** [comment]
What if you do a merge(join) instead. The group column will be the key, and you get all the rows from both sides? Is that the kind of output you're looking at?

**Comment by D3SL** [comment]
A self full join in the pattern of ```full_join(comparison_df[comparison_df$key == 'new'], comparison_df[comparison_df$key == 'old'], by='groupcol')``` is just another way of doing the same thing as pivoting to long then back to wide, it just manages to keep the chng_type column where pivoting loses it. In both cases the user needs to add a redundant column to each dataframe whose only purpose is to track whether a row is from the old or new dataframe, and in both cases the comparison's group column comes out with all rows from both objects, only the remaining columns are in the ```old.x, new.x``` format.

In neither case do you get a true side by side comparison with _all_ columns separated by old object and new object like so:

```
chng_type    x.old     y.old     z.old     x.new     y.new     z.new
    +         NA        NA        NA       1           1         1
    -         1        1        1          NA          NA        NA
    ~         1        1        1          2           2        2
     
```

The closest that you can get is this:

```
chng_type    x     y.old     z.old     y.new     z.new
    +         1        NA       NA       1         1
    -         1        1        1        NA        NA
    -         1        1        1        NA        NA
    +         2        NA       NA       2         2
     
```

**Comment by D3SL** [comment]
I tested that workaround idea and found it easiest to do with data.table:

```
testdata$comparison_df[key=='old',x.old:=x]
testdata$comparison_df[key=='new',x.new:=x]

**Comment by alexsanjoseph** [comment]
@D3SL - Glad you found a workaround.

Yeah currently the code is not built for performance, I'm not sure if I'll come around to rewriting this in RCpp which would be vastly better. The tests are pretty comprehensive, so if you have expertise in this, it would be great.

Is there anything further or shall I close this?

**Comment by D3SL** [comment]
I don't know enough C to do something this complicated unfortunately. I do know my way around data.table though, which could still be a significant performance improvement over dplyr as the core.

**Comment by alexsanjoseph** [comment]
Yeah data.table might be a good compromise. I'll add an enhancement to see if I can do it in data.table. Thanks for the inputs!

**Comment by alexsanjoseph** [comment]
#35
