### ISSUE TITLE
Using this with spark-shell

### ISSUE THREAD

**Issue by mahbubur-rahman-healthiq** [alexsanjoseph/compareDF#4]
Hi,

I am trying to use this tool with spark-shell. Unfortunately it is not working. Is there any guideline for spark-shell?

**Comment by alexsanjoseph** [comment]
Hi,

I haven't really worked with spark-shell, so I don't have this planned at all. I'd be glad to support you if you have an idea on how to proceed.

**Comment by mahbubur-rahman-healthiq** [comment]
Hi,

Sorry I thought it was an extension of Spark as Spark also has Data Frame! However, now it is clear that it is an extension of R.

I got it working now in Windows. I am a bit struggling to get it working on Centos or Ubuntu.

BTW, it is a nice tool and exactly what I was looking to test my new ETL development result with the previous.

I would be interested in contributing to this project.

Kind regards,
Sumon

**Comment by alexsanjoseph** [comment]
Sure Sumon, I'll be glad to have your help you fix any new issues :)
