### ISSUE TITLE
`gather_()` was deprecated in tidyr 1.2.0.

### ISSUE THREAD

**Issue by jaw8** [alexsanjoseph/compareDF#47]
**Describe the bug**
Function `create_change_count()` is using `tidyr::gather_()`, which is depreciated.

**To Reproduce**
Run normal `compareDF::compare_df()`

**Expected behavior**
No warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/62952761/158027764-81808246-876f-4dfa-bf60-f25d250a88b2.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
Version 21H2
OS build 22000.556
 - R: v4.1.2
 - RStudio: 2022.02.0 Build 443

**Additional context**
None.

**Comment by alexsanjoseph** [comment]
Latest version to be on CRAN fixes this.
