### ISSUE TITLE
create_table_output arguments not used for xlsx output

### ISSUE THREAD

**Issue by jeffdmoore8** [alexsanjoseph/compareDF#51]
**Describe the bug**
The `change_col_name` argument is not used when creating an xlsx output using the `create_table_output` function.

**To Reproduce**

```r
library(compareDF)

compare_result <- compare_df(results_2010, results_2011, group_col = ‘Student’)

# Change column renamed to ‘Source’
create_output_table(compare_result, change_col_name = ‘Source’, output_type = ‘html’)

# Change column is not renamed.
create_output_table(compare_result, change_col_name = ‘Source’, output_type = ‘xlsx’, file_name = ‘output.xlsx’) 
```

**Expected behavior**
Change column is renamed to value from `change_col_name` argument.

**Comment by alexsanjoseph** [comment]
Thanks for the issue - Will you be able to check if https://github.com/alexsanjoseph/compareDF/pull/52 fixes the issue?

**Comment by jeffdmoore8** [comment]
Yes, looks good!
