### ISSUE TITLE
Throw warning on identical table rather than error

### ISSUE THREAD

**Issue by condwanaland** [alexsanjoseph/compareDF#7]
Awesome package! For automated report generation, it would be really helpful if  `check_if_comparable` and `check_if_similar_after_unique_and_reorder` (and friends) would throw a warning rather than an error. This allows batches of reports to continue if some data hasn't changed.

Is this something you'd consider implementing. If you're very busy I could try sending the pull request myself

**Comment by alexsanjoseph** [comment]
Hi @condwanaland - Thanks for the praise and suggestions. I'll implement them soon :)

**Comment by alexsanjoseph** [comment]
@condwanaland - I've updated the packages. Can you do a dev install and see if it works? It'll be uploaded to CRAN soon.

**Comment by condwanaland** [comment]
@alexsanjoseph Thanks for much for the quick update! Just been testing it, it all seems to be working as far as I can tell. Tested on a wide variety of datasets. 

A CRAN upload would be greatly appreciated, as work blocks me from doing github installs :)

**Comment by alexsanjoseph** [comment]
I've uploaded the package to CRAN. You should see it in effect in a few hours. Just out of curiosity - can you tell me what features do you use in the package? Is this the comparison function or rendering of the HTML?

**Comment by condwanaland** [comment]
I basically build systems that automatically clean and check data for quality. So I use the comparison function in essentially every report I build. More often than not I'll then generate the html output as its great for the non-technical members of my team to inspect, but it does depend on the dataset

**Comment by alexsanjoseph** [comment]
Got it! thanks for the info :). Closing the issue
